apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ include "resourcebot.fullname" . }}-efs-pv"
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.volumeHandle }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "resourcebot.fullname" . }}-efs-claim"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
